# Statistical Methods with numpy

In [1]:
import numpy as np

In [2]:
x= np.array([[1,2,3], [4,5,6], [7,8,9]])  #2D Matrix, 3*3 matrix
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
np.sum(x) #summation of entire array elements

45

In [7]:
sum(x) #summation of all the columns 

array([12, 15, 18])

In [8]:
np.min(x) #shows the minimum valued element

1

In [9]:
np.max(x) #shows the maximum valued element

9

In [10]:
np.mean(x)

5.0

In [16]:
list = [7,1,13,16]
sum_list = sum(list)
length_sum = len(list)
mean = sum_list/ length_sum
mean

9.25

In [17]:
np.mean(list)  #numpy makes the tasks easier
#calculating mean

9.25

In [18]:
list1 = np.array(list)
np.mean(list1)

9.25

In [19]:
list1

array([ 7,  1, 13, 16])

In [20]:
np.std(list1)  #claculating stndard deviation

5.7608593109014565