#### Creating Matrix

##### list

In [1]:
a = [1, 2,3]  #one dimensional list
a

[1, 2, 3]

In [2]:
a = [[1,2], [3,4]]  #two dimensional matrix with two rows(row 0, 1) and columns(column 0, 1)
a                   #nested list are created to create matrix 

[[1, 2], [3, 4]]

In Machine learning concepts such as in CNN algorithm, when we train images then they need to be converted in numerical form. In this case, images are converted into lots of pixels that is in RGB value format. These pixels would be stored in two dimensional value as matrix. To analyze the matrix, we need to know the use of numpy library.  **Images are represented as two dimensional array.**

### Import library

In [3]:
import numpy as np #importing numpy library in short form as np 

In [4]:
np    #shows the module numpy

<module 'numpy' from 'C:\\Users\\sunan\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

## Creating Matrix : np.array()

In [5]:
x= np.array([[1,2,3], [4,5,6], [7,8,9]])  #2D Matrix, 3*3 matrix
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Matrix Indexing

In [6]:
x[0,2]  #0th row and 3rd column(starts from 0)
#accessing single element

3

In [9]:
x[2,1] #3rd row and 2nd column(starts from 0)  #this way is recommended

8

In [12]:
x[2][1]

8

In [10]:
#access the entire row of a matrix

x[0] #will show an array

array([1, 2, 3])

In [11]:
print(x[0]) #will show a list

[1 2 3]


### Matrix Slicing

x[i,j]

x[ i1:i2 , j1:j2]

In [13]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
 x[0:2,1:2] 

In [21]:
x[:2,:2]

array([[1, 2],
       [4, 5]])

In [22]:
x[0:2,] 

array([[1, 2, 3],
       [4, 5, 6]])

#### Checking the shape of the matrix

In [29]:
x.shape

(3, 3)

In [24]:
y= x[0:2,1:2] 

In [26]:
y 

array([[2],
       [5]])

In [28]:
y.shape  #checking the shape of the matrix

(2, 1)

In [30]:
z= np.array([[10,20,30], [40,50,60]])
z.shape

(2, 3)

## Accessing rows and columns

In [35]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
x[:,2] #accessing column
#shows 3rd column values for all the rows

array([3, 6, 9])

In [33]:
x[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [34]:
x[:2,0:2]

array([[1, 2],
       [4, 5]])

In [36]:
x[ : , :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
x[ : , :-1]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [38]:
x[ :-1 , :-1]

array([[1, 2],
       [4, 5]])

In [46]:
x[ :-2 , :1]

array([[1]])

In [47]:
x[ :-2 , :2]

array([[1, 2]])

In [48]:
x[ :-2 , :3]

array([[1, 2, 3]])

In [55]:
x[ -1: , :1]

array([[7]])

In [56]:
x[ -1: , :2]

array([[7, 8]])

In [57]:
x[ -1: , :3]

array([[7, 8, 9]])

In [59]:
x[ -1: , -1:]

array([[9]])