# matrix operations

In [2]:
import numpy as np

In [3]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
y = np.array([[10,20,30],[40,50,60],[70,80,90]])
y

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Adding two matrices

In [5]:
np.add(x,y)

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

## Multiply two matrices

In [6]:
np.dot(x,y)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

## Transpose of matrix

In [7]:
np.transpose(x)    #Column becomes row and the row becomes the column

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Creating Zeros and Ones

In [8]:
z = np.zeros((4,4))   #we are mentioning the matrix rows and columns

In [9]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
z = np.zeros((4,4), dtype=int)
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
z = np.zeros((4,4), dtype=complex)
z

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])